/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theater;

import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fikrirazor
 */
public class editdata extends javax.swing.JFrame {

    /**
     * Creates new form editdata
     */
    int posX=0,posY=0;
    
    public editdata() {
        initComponents();
        load_table();
        kosong();
        setResizable(false); 
    }
      private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Studio");
        model.addColumn("No hp");
        model.addColumn("Studio");
        model.addColumn("Judul Film");
        model.addColumn("Waktu");
        model.addColumn("Seat no");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from menonton";
            java.sql.Connection conn=(Connection)connector.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            jTable2.setModel(model);
        } catch (Exception e) {
        }
    }
    private void kosong(){
        TxtHp.setText(null);
        TxtName.setText(null);
        TxtSeat.setText(null);
        TxtStudio.setText(null);
        TxtTime.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        clearbtn = new javax.swing.JLabel();
        emptybtn = new javax.swing.JLabel();
        editbutton = new javax.swing.JLabel();
        addbtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtHp = new javax.swing.JTextField();
        TxtTime = new javax.swing.JTextField();
        TxtStudio = new javax.swing.JTextField();
        TxtSeat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(113, 170, 151));
        jPanel2.setBorder(null);
        jPanel2.setForeground(new java.awt.Color(191, 191, 205));
        jPanel2.setToolTipText("b");
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(105, 105, 105));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(113, 170, 151));

        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clearallblack.png"))); // NOI18N
        clearbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clearbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clearbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearbtnMouseEntered(evt);
            }
        });

        emptybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deleteblack.png"))); // NOI18N
        emptybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emptybtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emptybtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emptybtnMouseEntered(evt);
            }
        });

        editbutton.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        editbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b.png"))); // NOI18N
        editbutton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        editbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editbuttonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editbuttonMouseEntered(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(1, 1, 1));
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addblack.png"))); // NOI18N
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbtnMouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(113, 170, 151));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Harga");

        TxtName.setBackground(new java.awt.Color(113, 170, 151));
        TxtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtName.setSelectedTextColor(new java.awt.Color(254, 254, 254));
        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        TxtHp.setBackground(new java.awt.Color(113, 170, 151));
        TxtHp.setBorder(null);

        TxtTime.setBackground(new java.awt.Color(113, 170, 151));
        TxtTime.setBorder(null);
        TxtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTimeActionPerformed(evt);
            }
        });

        TxtStudio.setBackground(new java.awt.Color(113, 170, 151));
        TxtStudio.setBorder(null);
        TxtStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStudioActionPerformed(evt);
            }
        });

        TxtSeat.setBackground(new java.awt.Color(113, 170, 151));
        TxtSeat.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Movie Name");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("No Hp");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Show Time");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Nama Studio");

        jSeparator2.setBackground(new java.awt.Color(0, 57, 38));
        jSeparator2.setForeground(new java.awt.Color(0, 57, 38));

        jSeparator3.setBackground(new java.awt.Color(0, 57, 38));
        jSeparator3.setForeground(new java.awt.Color(0, 57, 38));

        jSeparator4.setBackground(new java.awt.Color(0, 57, 38));
        jSeparator4.setForeground(new java.awt.Color(0, 57, 38));

        jSeparator5.setBackground(new java.awt.Color(0, 57, 38));
        jSeparator5.setForeground(new java.awt.Color(0, 57, 38));

        jSeparator6.setBackground(new java.awt.Color(0, 57, 38));
        jSeparator6.setForeground(new java.awt.Color(0, 57, 38));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(254, 254, 254));
        jTable2.setBorder(null);
        jTable2.setForeground(new java.awt.Color(1, 1, 1));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Studio", "No Hp", "Studio", "Judul Film", "Waktu", "No Kursi"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(254, 254, 254));
        jTable2.setSelectionBackground(new java.awt.Color(66, 176, 244));
        jTable2.setSelectionForeground(new java.awt.Color(1, 1, 1));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator4)
                    .addComponent(TxtHp)
                    .addComponent(TxtTime)
                    .addComponent(TxtStudio)
                    .addComponent(TxtSeat)
                    .addComponent(TxtName)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtHp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emptybtn)
                    .addComponent(clearbtn)
                    .addComponent(editbutton)
                    .addComponent(addbtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addbtn)
                .addGap(18, 18, 18)
                .addComponent(editbutton)
                .addGap(18, 18, 18)
                .addComponent(clearbtn)
                .addGap(18, 18, 18)
                .addComponent(emptybtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void TxtStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStudioActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int baris = jTable2.rowAtPoint(evt.getPoint());
        String Nama_studio =jTable2.getValueAt(baris, 1).toString();
        TxtStudio.setText(Nama_studio);
        String hp = jTable2.getValueAt(baris,2).toString();
        TxtHp.setText(hp);
        String time = jTable2.getValueAt(baris, 5).toString();
        TxtTime.setText(time);
        String name=jTable2.getValueAt(baris, 4).toString();
        TxtName.setText(name);
        String seat = jTable2.getValueAt(baris, 6).toString();
        TxtSeat.setText(seat);
    }//GEN-LAST:event_jTable2MouseClicked

    private void TxtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTimeActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        posX=evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_formMouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        posX=evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void addbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseEntered
        addbtn.setToolTipText("Klik Icon ini untuk menambahkan data.");
    }//GEN-LAST:event_addbtnMouseEntered

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        try {
            String sql = "INSERT INTO menonton VALUES ('"+TxtStudio.getText()+"','"+TxtHp.getText()+"','"+TxtName.getText()+"','"+TxtTime.getText()+"','"+TxtSeat.getText()+"')";
            java.sql.Connection conn=(Connection)connector.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_addbtnMouseClicked

    private void addbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/addblack.png"));
        addbtn.setIcon(II);
    }//GEN-LAST:event_addbtnMouseReleased

    private void addbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/addwhite.png"));
        addbtn.setIcon(II);
    }//GEN-LAST:event_addbtnMousePressed

    private void editbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbuttonMouseEntered
        editbutton.setToolTipText("Klik Icon ini untuk mengedit data.");
    }//GEN-LAST:event_editbuttonMouseEntered

    private void editbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbuttonMouseClicked
        try {
            String sql ="UPDATE menonton SET Judul_film = '"+TxtName.getText()+"', no_hp = '"+TxtHp.getText()+"',waktu = '"+TxtTime.getText()+"',Nama_studio = '"+TxtStudio.getText()+"',no_kursi = '"+TxtSeat.getText()+"' WHERE no_hp = '"+TxtHp.getText()+"'";
            java.sql.Connection conn=(Connection)connector.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_editbuttonMouseClicked

    private void editbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbuttonMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/b.png"));
        editbutton.setIcon(II);
    }//GEN-LAST:event_editbuttonMouseReleased

    private void editbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbuttonMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/a.png"));
        editbutton.setIcon(II);
    }//GEN-LAST:event_editbuttonMousePressed

    private void clearbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseEntered
        clearbtn.setToolTipText("Klik Icon ini untuk membersihkan cepat.");
    }//GEN-LAST:event_clearbtnMouseEntered

    private void clearbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseClicked
        kosong();
    }//GEN-LAST:event_clearbtnMouseClicked

    private void clearbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/clearallblack.png"));
        clearbtn.setIcon(II);
    }//GEN-LAST:event_clearbtnMouseReleased

    private void clearbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/clearallwhite.png"));
        clearbtn.setIcon(II);
    }//GEN-LAST:event_clearbtnMousePressed

    private void emptybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptybtnMouseEntered
        emptybtn.setToolTipText("Klik Icon ini untuk menghapus data.");
    }//GEN-LAST:event_emptybtnMouseEntered

    private void emptybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptybtnMouseClicked
        try {
            String sql ="delete from menonton where No_hp='"+TxtHp.getText()+"'";
            java.sql.Connection conn=(Connection)connector.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_emptybtnMouseClicked

    private void emptybtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptybtnMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/deleteblack.png"));
        emptybtn.setIcon(II);
    }//GEN-LAST:event_emptybtnMouseReleased

    private void emptybtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptybtnMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/deletewhite.png"));
        emptybtn.setIcon(II);
    }//GEN-LAST:event_emptybtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHp;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtSeat;
    private javax.swing.JTextField TxtStudio;
    private javax.swing.JTextField TxtTime;
    private javax.swing.JLabel addbtn;
    private javax.swing.JLabel clearbtn;
    private javax.swing.JLabel editbutton;
    private javax.swing.JLabel emptybtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
